{
  "formatVersion": "1.1",
  "component": {
    "group": "fr.litarvan",
    "module": "openauth",
    "version": "1.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "openauth-1.1.3.jar",
          "url": "openauth-1.1.3.jar",
          "size": 48512,
          "sha512": "07abc38c67998d53bfdbd32d1e6d51c023e8db05fdaf1d47ae702cce7d6b56767faa00a90a106411aebc516d8e304d0d5ff02531921a58657af1b004881c3696",
          "sha256": "1b0b029a23da84acfbbb66b95c18db6c7006499da770a7c95428c6f86ee76941",
          "sha1": "5a5fe346d52d24db70e8a55c5838afe4376de620",
          "md5": "d80de0488cd626ba98034b4af99e9764"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "11.0.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "mac"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "11.0.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "mac"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-controls",
          "version": {
            "requires": "11.0.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-controls",
              "type": "jar",
              "extension": "jar",
              "classifier": "mac"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-media",
          "version": {
            "requires": "11.0.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-media",
              "type": "jar",
              "extension": "jar",
              "classifier": "mac"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-swing",
          "version": {
            "requires": "11.0.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-swing",
              "type": "jar",
              "extension": "jar",
              "classifier": "mac"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-web",
          "version": {
            "requires": "11.0.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-web",
              "type": "jar",
              "extension": "jar",
              "classifier": "mac"
            }
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "openauth-1.1.3.jar",
          "url": "openauth-1.1.3.jar",
          "size": 48512,
          "sha512": "07abc38c67998d53bfdbd32d1e6d51c023e8db05fdaf1d47ae702cce7d6b56767faa00a90a106411aebc516d8e304d0d5ff02531921a58657af1b004881c3696",
          "sha256": "1b0b029a23da84acfbbb66b95c18db6c7006499da770a7c95428c6f86ee76941",
          "sha1": "5a5fe346d52d24db70e8a55c5838afe4376de620",
          "md5": "d80de0488cd626ba98034b4af99e9764"
        }
      ]
    }
  ]
}
